### ISSUE TITLE
传输的数据后面会跟随乱码

### ISSUE THREAD

**Issue by Cpt-Lee** [eternal-echo/WirelessUART#1]
博主您好，我将程序烧录进8266后进行测试，输出的结果会跟随一串乱码，不论是主机向从机发送或是反过来都有这个问题。具体情况如图：
![image](https://github.com/eternal-echo/WirelessUART/assets/56884700/96f736bf-68a6-4ac0-aab8-8087fb007f34)
这种情况我应该如何处理呢？

**Comment by Yooofox** [comment]
我猜你是用的知乎上的代码，你用Github上的代码试试，或者把 buf[i] = '\\0'; 改成 buf[i] = '\0';
